server:
  port: 8001
  servlet:
    context-path: /web-app
spring:
  application:
    name: web-app
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://webdb:5432/web
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    url: jdbc:postgresql://webdb:5432/web
    user: postgres
    password: postgres
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:8761/eureka/}
  instance:
    instance-id: web-app