server:
  port: 8003
  servlet:
    context-path: /data_base-app
spring:
  application:
    name: data-base
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://databasedb:5432/data
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    url: jdbc:postgresql://databasedb:5432/data
    user: postgres
    password: postgres
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:8761/eureka/}
  instance:
    instance-id: data-base