server:
  port: 8003
  servlet:
    context-path: /data_base-app
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://databasedb:5432/data
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres