version: '3.3'

services:

  discovery:
    container_name: discovery
    build: ./discovery
    image: zemec:discovery
    ports:
      - "8761:8761"
    environment:
    - EUREKA_HOST=http://discovery:8761/eureka/

  web-app:
    container_name: web-app
    build: ./web-app
    image: zemec:web-app
    depends_on:
      - webdb
      - database-app
    ports:
      - "8001:8001"
    environment:
    - EUREKA_HOST=http://discovery:8761/eureka/

  database-app:
    container_name: data_base-app
    build: ./data_base-app
    image: zemec:data_base-app
    depends_on:
      - databasedb
      - discovery
    ports:
      - "8003:8003"
    environment:
    - EUREKA_HOST=http://discovery:8761/eureka/

  databasedb:
    hostname: databasedb
    image: postgres:13.4-alpine
    env_file:
      - ./database-db/database.env
    volumes:
      - ./database-db/data.sql:/docker-entrypoint-initdb.d/data.sql
      - ./database-db/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  webdb:
    hostname: webdb
    image: postgres:13.4-alpine
    env_file:
      - ./web-db/database.env
    volumes:
      - ./web-db/data.sql:/docker-entrypoint-initdb.d/data.sql
      - ./web-db/data:/var/lib/postgresql/data
    ports:
      - "5434:5432"